Import environments from puppet
theforeman/foreman_puppet pull request #133
Opened 2021-04-16 09:34 UTC by kamils-iRonin

2021-04-16 09:55 UTC, timogoebel commented
I believe this fixes #131.

2021-04-16 11:03 UTC, ezr-ondrej requested changes
I believe the STI hacks are not necessary (if we are using the plugin's importer), and I'd like to have at least PR dropping the template from core, before merge.

Apart of it great find, and looks like a correct fix (didn't tested yet)! :+1:

2021-04-16 11:04 UTC, ezr-ondrej commented on app/controllers/concerns/foreman_puppet/environments_import.rb
> +        render 'foreman_puppet/common/_puppetclasses_or_envs_changed'
> Could you please also open a PR against https://github.com/ezr-ondrej/foreman/tree/puppet_extraction dropping this template?
> Or shall I do so? :)

2021-04-16 11:59 UTC, laugmanuel commented
Looks like a great fix for #131.
I've tested and verified that the correct endpoints get used for:
- importing all environments from the smartproxy
- importing a specific environment
- importing classes/parameters

2021-04-16 12:09 UTC, timogoebel commented on app/models/foreman_puppet/puppetclass_lookup_key.rb
> +    # TODO: when the puppet support is dropped from the core, add a migration that renames the type to ForemanPuppet::PuppetclassLookupKey
Is it possible that there are some "leftovers" in the database because the "old" endpoints were used after this plugin was installed?

2021-04-16 12:36 UTC, ezr-ondrej commented on app/models/foreman_puppet/puppetclass_lookup_key.rb
> +    # TODO: when the puppet support is dropped from the core, add a migration that renames the type to ForemanPuppet::PuppetclassLookupKey
That sounds quite likely, that could be the issue.

2021-04-16 14:14 UTC, kamils-iRonin commented on app/models/foreman_puppet/puppetclass_lookup_key.rb
> +    # TODO: when the puppet support is dropped from the core, add a migration that renames the type to ForemanPuppet::PuppetclassLookupKey
that's the case, thanks! I re-tested it on a clean database and it seems to be working fine

2021-04-19 18:32 UTC, timogoebel approved these changes

2021-04-20 14:26 UTC, ezr-ondrej commented
Thanks @kamils-iRonin for fixing and @laugmanuel and @timogoebel for the reviews! :+1:

2021-04-20 14:26 UTC, merged