Drop environment columns from core tables
theforeman/foreman_puppet pull request #271
Opened 2022-04-21 20:47 UTC by ezr-ondrej

Fixes #270

2022-04-22 08:41 UTC, nadjaheitmann requested changes
If you change the name of the migration, you need also change the file name I guess :)

2022-04-22 08:41 UTC, nadjaheitmann commented on db/migrate/20220421204325_drop_environment_from_host_and_hg.foreman_puppet.rb
> +class DropEnvironmentEnvironmentFromHostAndHg < ActiveRecord::Migration[6.0]
```suggestion
class DropEnvironmentFromHostAndHostgroup < ActiveRecord::Migration[6.0]
```

2022-04-22 08:41 UTC, nadjaheitmann commented on db/migrate/20220421204325_drop_environment_from_host_and_hg.foreman_puppet.rb
> +  def up
```suggestion
  def down
```

2022-04-22 08:43 UTC, nadjaheitmann commented
From my understanding of Rails, this migration would run as one of the first ones. Don't you think that some other tables need to be cleaned up, first?

2022-04-22 09:29 UTC, nadjaheitmann commented
I just found this in the migrations: https://github.com/theforeman/foreman_puppet/blob/master/db/migrate/20211112130803_cleanup_environment_from_core_tables.foreman_puppet.rb

Maybe your code could also be part of this migration.

2022-04-22 09:35 UTC, nadjaheitmann commented
Also, from my understanding, this will not yet solve #271 because the error does not occur on installation but on uninstallation, so we need a down migration to solve this?

2022-04-22 11:47 UTC, ezr-ondrej commented
> I just found this in the migrations: https://github.com/theforeman/foreman_puppet/blob/master/db/migrate/20211112130803_cleanup_environment_from_core_tables.foreman_puppet.rb

You're right, seeing this, that should prevent the error on uninstallations :thinking:

2022-04-22 11:47 UTC, ezr-ondrej commented
> because the error does not occur on installation but on uninstallation, so we need a down migration to solve this?

This would remove the column on up migrations, so there would be no issue on down migrations.

2022-04-22 11:55 UTC, nadjaheitmann commented
> This would remove the column on up migrations, so there would be no issue on down migrations (uninstall) with this column.

The guy who had the problems of removing the Puppet data never installed the plugin in the first place, just foreman core. So any up migrations we add to the plugin code are not run for people who are just dropping the data they don't need. While upgrading from 2.5, you can choose whether to install the plugin or not.

2022-04-25 12:18 UTC, nadjaheitmann commented
> The guy who had the problems of removing the Puppet data never installed the plugin in the first place, just foreman core. So any up migrations we add to the plugin code are not run for people who are just dropping the data they don't need. While upgrading from 2.5, you can choose whether to install the plugin or not.

I see that he did via foreman-installer, you don't on the manual upgrade. So when you downgrade, eventually this is run:
https://github.com/theforeman/foreman_puppet/blob/master/db/migrate/20200803113803_migrate_environment_to_puppet_facet.foreman_puppet.rb

It moves the data back in the original db tables because the column still exists, it has not yet been dropped anywhere.

2022-04-25 13:28 UTC, ezr-ondrej commented
> It moves the data back in the original db tables because the column still exists, it has not yet been dropped anywhere.

Right, so this should be the best path forward afterall

2022-04-25 18:55 UTC, ezr-ondrej commented
Test fix: https://github.com/theforeman/foreman_puppet/pull/272

2022-04-27 11:56 UTC, nadjaheitmann approved these changes

2022-04-27 13:16 UTC, merged

2022-04-27 15:32 UTC, nadjaheitmann commented
CP 2.0: 8401180257a88c7442c1ef82816ca0db396c39db