Fixes #36421 - do not load non-existant charts.js
theforeman/foreman_puppet pull request #352
Opened 2023-05-22 05:58 UTC by evgeni

We used charts.js from Foreman, but that was dropped in Foreman 3.0 (https://github.com/theforeman/foreman/commit/69379b51a33344de93836950565ecbfae0c4df23) and results in 404 errors when trying to load the smart proxy details page.

2023-05-22 06:17 UTC, evgeni commented
Huh. Seems there actually is a broken chart (not that it was working before I removed the loading of the non-existant file, but…)

2023-05-22 06:35 UTC, evgeni commented on app/views/smart_proxies/plugins/_puppet.html.erb
> -    <div class="clearfix row container-cards-pf container-fluid" data-ajax-url="<%= foreman_puppet.dashboard_puppet_smart_proxy_path(@smart_proxy) %>" data-on-complete="refreshCharts"><%= spinner %><
this function came from charts.js :woman_shrugging:

2023-05-23 07:35 UTC, nadjaheitmann commented
Thanks @evgeni . Does this fix https://github.com/theforeman/foreman_puppet/issues/307 ? 
And @stejskalleos tests are failing with `ActionView::Template::Error: DEPRECATION WARNING: The asset "foreman_puppet/locale/en/foreman_puppet.js" is not present in the asset pipeline.` Is this related to the translations update?

2023-05-23 08:12 UTC, evgeni commented
No, this should have no effect on 307.

2023-06-06 08:43 UTC, stejskalleos requested changes
https://github.com/theforeman/foreman_puppet/pull/353 merged, please rebase so we can have green tests

2023-06-06 09:38 UTC, merged